# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first_des.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FORM(object):
    def setupUi(self, FORM):
        FORM.setObjectName("FORM")
        FORM.resize(1001, 601)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FORM.sizePolicy().hasHeightForWidth())
        FORM.setSizePolicy(sizePolicy)
        FORM.setMinimumSize(QtCore.QSize(1030, 601))
        FORM.setMaximumSize(QtCore.QSize(1030, 601))
        self.layoutWidget = QtWidgets.QWidget(FORM)
        self.layoutWidget.setGeometry(QtCore.QRect(0, -20, 1030, 620))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.localLabel = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.localLabel.sizePolicy().hasHeightForWidth())
        self.localLabel.setSizePolicy(sizePolicy)
        self.localLabel.setMinimumSize(QtCore.QSize(200, 510))
        self.localLabel.setMaximumSize(QtCore.QSize(200, 510))
        self.localLabel.setObjectName("localLabel")
        self.verticalLayout.addWidget(self.localLabel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.line_2 = QtWidgets.QFrame(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        self.line_2.setMinimumSize(QtCore.QSize(10, 50))
        self.line_2.setMaximumSize(QtCore.QSize(10, 50))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        self.text = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text.sizePolicy().hasHeightForWidth())
        self.text.setSizePolicy(sizePolicy)
        self.text.setMinimumSize(QtCore.QSize(180, 20))
        self.text.setMaximumSize(QtCore.QSize(180, 20))
        self.text.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.text.setObjectName("text")
        self.horizontalLayout_2.addWidget(self.text)
        self.line = QtWidgets.QFrame(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMinimumSize(QtCore.QSize(10, 50))
        self.line.setMaximumSize(QtCore.QSize(10, 50))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(25, 40, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Button = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button.sizePolicy().hasHeightForWidth())
        self.Button.setSizePolicy(sizePolicy)
        self.Button.setMinimumSize(QtCore.QSize(150, 40))
        self.Button.setMaximumSize(QtCore.QSize(150, 40))
        self.Button.setObjectName("Button")
        self.horizontalLayout.addWidget(self.Button)
        spacerItem1 = QtWidgets.QSpacerItem(25, 40, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.imgLabel = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imgLabel.sizePolicy().hasHeightForWidth())
        self.imgLabel.setSizePolicy(sizePolicy)
        self.imgLabel.setMinimumSize(QtCore.QSize(600, 600))
        self.imgLabel.setMaximumSize(QtCore.QSize(600, 600))
        self.imgLabel.setObjectName("imgLabel")
        self.horizontalLayout_3.addWidget(self.imgLabel)
        self.globalLabel = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.globalLabel.sizePolicy().hasHeightForWidth())
        self.globalLabel.setSizePolicy(sizePolicy)
        self.globalLabel.setMinimumSize(QtCore.QSize(200, 600))
        self.globalLabel.setMaximumSize(QtCore.QSize(200, 600))
        self.globalLabel.setObjectName("globalLabel")
        self.horizontalLayout_3.addWidget(self.globalLabel)

        self.retranslateUi(FORM)
        QtCore.QMetaObject.connectSlotsByName(FORM)

    def retranslateUi(self, FORM):
        _translate = QtCore.QCoreApplication.translate
        FORM.setWindowTitle(_translate("FORM", "Form"))
        self.localLabel.setText(_translate("FORM", "TextLabel"))
        self.text.setPlaceholderText(_translate("FORM", "              write here      "))
        self.Button.setText(_translate("FORM", "Edit new line"))
        self.imgLabel.setText(_translate("FORM", "TextLabel"))
        self.globalLabel.setText(_translate("FORM", "TextLabel"))

